
import {
  benefitIcon1,
  benefitIcon2,
  benefitIcon3,
  benefitIcon4,
  benefitImage2,
  chromecast,
  disc02,
  discord,
  discordBlack,
  facebook,
  figma,
  file02,
  framer,
  homeSmile,
  instagram,
  notification2,
  notification3,
  notification4,
  notion,
  photoshop,
  plusSquare,
  protopie,
  raindrop,
  recording01,
  recording03,
  roadmap1,
  roadmap2,
  roadmap3,
  roadmap4,
  searchMd,
  slack,
  sliders04,
  telegram,
  twitter,
  yourlogo,
  check,
  dash // Adding the dash icon for unavailable features
} from "../assets";

export const pricing = [
  {
    id: "0",
    title: "Basic",
    price: "125",
    features: [
      { description: "Custom Domain", available: false },
      { description: "Number of Pages: 3", available: true },
      { description: "SEO Optimization: Basic", available: true },
      { description: "E-commerce Capability", available: false },
      { description: "Mobile Optimization", available: true },
      { description: "Custom Design: Template-based", available: true },
      { description: "Customer Support: Email Only", available: true },
      { description: "Analytics Integration: Basic", available: true },
      { description: "Regular Updates", available: false },
    ],
  },
  {
    id: "1",
    title: "Premium",
    price: "225",
    features: [
      { description: "Custom Domain", available: true },
      { description: "Number of Pages: 10", available: true },
      { description: "SEO Optimization: Advanced", available: true },
      { description: "E-commerce Capability", available: true },
      { description: "Mobile Optimization", available: true },
      { description: "Custom Design: Semi-custom", available: true },
      { description: "Customer Support: Email & Chat", available: true },
      { description: "Analytics Integration: Standard", available: true },
      { description: "Regular Updates: Monthly", available: true },
    ],
  },
  {
    id: "2",
    title: "Enterprise",
    price: "375",
    features: [
      { description: "Custom Domain", available: true },
      { description: "Number of Pages: Unlimited", available: true },
      { description: "SEO Optimization: Comprehensive", available: true },
      { description: "E-commerce Capability", available: true },
      { description: "Mobile Optimization", available: true },
      { description: "Custom Design: Fully Custom", available: true },
      { description: "Customer Support: 24/7 Support", available: true },
      { description: "Analytics Integration: Advanced", available: true },
      { description: "Regular Updates: Weekly", available: true },
    ],
  },
];
